# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
pygments: true
markdown: kramdown

title: GrAppA
description: Gruppo Approfondimento Autogestito
author:
  name: GrAppA
  email: grappa@fiesta.cc
  github: unitn
  bio: Gruppo nato nel 2013 per riunire appassionati di Matematica e permettere a tutti di comunicare la loro idea.

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
rules_path: regolamento.html

#BASE_PATH: http://dbtek.github.io/dbyll

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
